# Generated by Django 5.0.4 on 2024-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='topics',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='year',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
