# Generated by Django 5.0.4 on 2024-04-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_topics_jsondata_topic_alter_jsondata_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='topic',
            new_name='topics',
        ),
    ]
