# Generated by Django 5.0.4 on 2024-04-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_topic_jsondata_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='year',
            new_name='end_year',
        ),
    ]
