# Generated by Django 5.0.4 on 2024-04-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_year_jsondata_end_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='end_year',
            new_name='year',
        ),
    ]
